http:
  routers:
    # Dagu Dashboard Route
    dagu-ui:
      rule: "Host(`dagu.localhost`)"
      entryPoints:
        - web
      service: dagu-service

    # Haupt-API des Workflow-Services
    workflow-router:
      rule: "PathPrefix(`/workflows`)"
      entryPoints:
        - web
      middlewares:
        - workflow-cors
      service: workflow-service

    # Swagger-Dokumentation (Mit CORS und Passwort-Schutz) admin, test
    workflow-docs:
      rule: "Path(`/api`) || PathPrefix(`/api/`)"
      entryPoints:
        - web
      middlewares:
        - workflow-cors
        - docs-auth
      service: workflow-service

    # Courses Service Route
    courses-router:
      rule: "PathPrefix(`/courses`) || PathPrefix(`/learning-materials`) || PathPrefix(`/assignments`) || PathPrefix(`/grades`) || PathPrefix(`/tasks`) || PathPrefix(`/task-progress`) || PathPrefix(`/content-releases`) || PathPrefix(`/content-templates`) || PathPrefix(`/groups`) || PathPrefix(`/search`)"
      entryPoints:
        - web
      middlewares:
        - workflow-cors
      service: courses-service

  middlewares:
    # CORS-Zertifikate für das Frontend
    workflow-cors:
      headers:
        accessControlAllowMethods:
          - GET
          - POST
          - PUT
          - DELETE
          - OPTIONS
        accessControlAllowOriginList:
          - "*"
        accessControlAllowHeaders:
          - Content-Type
          - Authorization

    # Passwortschutz für die Doku
    # admin, test
    docs-auth:
      basicAuth:
        users:
          # für neue zugangsdaten https://htpasswdgenerator.de/
          - "admin:$apr1$H6uskkkW$IgXLP6ewTrSuBkTrqE8wj/"

  # für viele Anfragen Round-Robin mit mehreren service definitionen wie url: "http://workflow-service-2:3000" oder halt k8s
  services:
    dagu-service:
      loadBalancer:
        servers:
          - url: "http://dagu:8080"

    workflow-service:
      loadBalancer:
        servers:
          - url: "http://workflow-service:3000"

    courses-service:
      loadBalancer:
        servers:
          - url: "http://courses-service:3000"