app:
  name: "workflow-service"

fullnameOverride: "workflow-service"

replicaCount: 1

image:
  repository: "wip-backend/workflow-service"
  tag: "latest"

imagePullSecrets:
  - name: github-ghcr

service:
  port: 3000

ingress:
  enabled: true
  path: "/workflows"